apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: eks-app
spec:
  selector:
    app: eks-user
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP