apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: eks-app
spec:
  selector:
    app: eks-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      #nodePort: 30080
  #type: NodePort
  type: ClusterIP