apiVersion: argoproj.io/v1alpha1
kind: Rollout # kind Rollout으로 변경
metadata:
  name: user-api
  namespace: eks-app
  labels:
    app: eks-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-user
  strategy: # blueGreen 전략으로 변경
    blueGreen:
      activeService: user-service # blue 서비스명
      previewService: user-service-preview # green 서비스명
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: eks-user
    spec:
      terminationGracePeriodSeconds: 10 # 빠른 종료
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: user
          image: 225989344665.dkr.ecr.us-west-2.amazonaws.com/hao/ticket_service:user-api-bcadf17e1087d51d61bdb0873b50010b0f46afa7-20250401121011
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DB_IP
              value: "haoticketdbcluster.cluster-czs4c6g4uy8h.us-west-2.rds.amazonaws.com"
            - name: DB_USER
              value: "worker_user"
            - name: DB_PASSWD
              value: "Dkagh1.!!"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m" # 최소 CPU 요청 (100m = 0.1 vCPU)
              memory: "128Mi" # 최소 메모리 요청
            limits:
              cpu: "500m" # 최대 CPU 사용량 (0.5 vCPU)
              memory: "256Mi" # 최대 메모리 사용량
      nodeSelector:
        kubernetes.io/os: linux
