apiVersion: argoproj.io/v1alpha1
kind: Rollout # kind Rollout으로 변경
metadata:
  name: reserve-api
  namespace: eks-app
  labels:
    app: eks-reserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-reserve
  strategy: # blueGreen 전략으로 변경
    blueGreen:
      activeService: reserve-service # blue 서비스명
      previewService: reserve-service-preview # green 서비스명
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: false
  template:
    metadata:
      labels:
        app: eks-reserve
    spec:
      terminationGracePeriodSeconds: 10 # 빠른 종료
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: reserve
          image: 225989344665.dkr.ecr.us-west-2.amazonaws.com/hao/ticket_service:TicketService-47cdf9f75f3289d5c8b87d6b5e0532a9223c9f12-20250404103513
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DB_IP
              value: "haoticketdbcluster.cluster-czs4c6g4uy8h.us-west-2.rds.amazonaws.com"
            - name: DB_USER
              value: "worker_user"
            - name: DB_PASSWD
              value: "Dkagh1.!!"
            - name: PORT
              value: "8000"
          command: ["/bin/sh", "-c"] # 쉘을 실행해서 명령어를 이어서 실행
          args:
            - "cd /TicketService_FastAPI_Streamlit/fastapi; python3 reserve_api/reserve.py"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      nodeSelector:
        kubernetes.io/os: linux
#  autoscaler:
#    minReplicas: 3
#    maxReplicas: 15
#    cpuUtilization:
#      targetPercentage: 65
#    memoryUtilization:
#      targetPercentage: 70
