apiVersion: v1
kind: Service
metadata:
  name: streamlit-service # blue 서비스명
  namespace: eks-app
spec:
  selector:
    app: eks-streamlit # 현재 activeService를 바라보도록 설정
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      #nodePort: 30080
  #type: NodePort
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service-preview # # Green을 미리보기(테스트)하는 서비스
  namespace: eks-app
spec:
  selector:
    app: eks-streamlit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
      #nodePort: 30080
  #type: NodePort
  type: ClusterIP