apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserve-api
  namespace: eks-app
  labels:
    app: eks-reserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-reserve
  template:
    metadata:
      labels:
        app: eks-reserve
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: reserve
          image: 225989344665.dkr.ecr.us-west-2.amazonaws.com/hao/ticket_service:TicketService-e4c039184bd93bfee69920209e3d9c79e2f93356-20250401165726
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DB_IP
              value: "haoticketdbcluster.cluster-ro-czs4c6g4uy8h.us-west-2.rds.amazonaws.com"
            - name: DB_USER
              value: "worker_user"
            - name: DB_PASSWD
              value: "Dkagh1.!!"
            - name: PORT
              value: "8000"
          command: ["/bin/sh", "-c"] # 쉘을 실행해서 명령어를 이어서 실행
          args:
            - |
              cd /TicketService_FastAPI_Streamlit/fastapi
              python3 reserve_api/reserve.py
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "250m" # 최소 CPU 요청 (250m = 0.25 vCPU)
              memory: "512Mi" # 최소 메모리 요청
            limits:
              cpu: "1" # 최대 CPU 사용량 (1 vCPU)
              memory: "1Gi" # 최대 메모리 사용량
      nodeSelector:
        kubernetes.io/os: linux
