apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: eks-app
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: streamlit-front  # 실제 프론트엔드 Deployment 이름
  minReplicas: 2  # 최소 파드 수
  maxReplicas: 6  # 최대 파드 수
  metrics:
    - type: Resource
      resource:
        name: cpu  # CPU 사용량을 기준으로 스케일링
        target:
          type: Utilization
          averageUtilization: 50 # CPU 사용량이 50%를 초과하면 스케일HPA업
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # 스케일업 지연 시간 없애기
      selectPolicy: Max  # 최대로 스케일업
      policies:
        - type: Percent
          value: 100  # 100% 확장
          periodSeconds: 30  # 30초 내에 스케일업 100%
    scaleDown:
      stabilizationWindowSeconds: 30  # 스케일다운 지연 시간 없애기
      selectPolicy: Min  # 최소로 스케일다운
      policies:
        - type: Percent
          value: 50  # 100% 축소
          periodSeconds: 30  # 30초 내에 스케일다운 100%
